//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.ImageTags = new HashSet<ImageTag>();
        }
    
        public int PKID { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ImageID { get; set; }
        public Nullable<int> ImageTypeID { get; set; }
        public string ImageURL { get; set; }
        public string ImageDescription { get; set; }
    
        public virtual ImageType ImageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageTag> ImageTags { get; set; }
    }
}
